#!/usr/bin/env python

import os,sys,glob
a = '''#$ -N .mgen%s
#$ -V
#$ -cwd
#$ -S /bin/bash
#$ -q all.q@n100
'''

formula  = sys.argv[1] 
#shdir  = '/home/lab01/RUCGUI/shfileBOX/'
shname="job%s"%(formula)
fw = open('%s.sh'%(shname), 'w')	
fw.write(a%(formula))
fw.write('python /home/lab01/RUCGUI/_qsmolgen.py %s'%(formula))

fw.close()	
os.system('qsub %s.sh'%(shname))
os.system('rm %s.sh'%(shname))
